### ISSUE TITLE
Higher order

### ISSUE THREAD

**Issue by c-blake** [theAkito/nim-fletcher#1]
You may or may not be aware of higher order Fletcher variations (mentioned in Fletcher's original paper, actually, and so still deserving of his name) for increased sensitivity at some cost in speed.  I have an example of a 3rd order at the top of `cligen/strUt.nim` in https://github.com/c-blake/cligen (mostly just used for the demo program `examples/dups.nim` there).

**Comment by theAkito** [comment]
Greetings and thank you for your post, @c-blake .

I briefly looked at your mentioned code and it indeed looks cool. The intention of my fletcher module was to have a quick and easy implementation possibility. I especially focus generally on my modules being accessible to as many users as possible, to basically make them user-friendly.
The second goal, as described in the [README](https://github.com/Akito13/nim-fletcher#what-is-this), is to have a speedy algorithm, which is why I chose this one in the first place.
That is why I don't know if I would implement a higher order Fletcher variation, like the one you are describing. On the other hand, you already did most of the work, so I might just implement it additionally (as an optional feature decided at compile time, for example), though I'm not sure as of now.
I'll have to think about it and look more into it.

Anyway, thank you very much for the information, as I indeed was not aware of higher order Fletcher variations. By itself, I find it very interesting, nonetheless and your implementation seems to feature some custom modifications, as well.

Thank you and if you have any further comment or info in general to share, please don't hesitate to do so. 😃

**Comment by c-blake** [comment]
2nd and 3rd order are still very fast (much faster than, say CRCs) in my experiments, though it's true 1st is the fastest.  How fast you need mostly depends on your situation.  For example, it might be faster than DIMM bandwidth up to 5th order.  So, if you knew you would usually be hitting DIMMs for data you might not care.  Or what happens upon a false collision might be particularly expensive.  Context almost always matters to optimize costs.  Anyway, the higher order seems underappreciated in the world at large.  So, I thought I'd mention it.
